#!/usr/bin/bash

for i in "./" "archive/";
do
  echo "Converting $i"
  tmp=$(mktemp)
  cat meta/prologue.html meta/header.html > $tmp 
  evblog $i -p $tmp -e meta/epilogue.html
  rm $tmp
done

echo "Converting blog/"
tmp=$(mktemp)
cat meta/prologue.html meta/header.html > $tmp 
cd blog/
evblog . -p $tmp -e meta/epilogue_comments.html -i meta/index.toml
rm $tmp

echo "Reformatting blog/index.html"
tmp=$(mktemp)
cat meta/prologue.html ../meta/header.html > $tmp 
evblog index.md -p $tmp -e meta/epilogue_plain.html
cd ../
rm $tmp
